/**
 * BlockBookmark automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BlockBookmark extends Block {
    private Bookmark bookmark;

    @JsonSetter("bookmark")
    public void setBookmark(Bookmark bookmark) {
        this.bookmark = bookmark;
    }

    @JsonGetter("bookmark")
    public Bookmark getBookmark() {
        return this.bookmark;
    }
}

