/**
 * BlockChildDatabase automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BlockChildDatabase extends Block {
    private ChildDatabase childDatabase;

    @JsonSetter("child_database")
    public void setChildDatabase(ChildDatabase childDatabase) {
        this.childDatabase = childDatabase;
    }

    @JsonGetter("child_database")
    public ChildDatabase getChildDatabase() {
        return this.childDatabase;
    }
}

