/**
 * BlockEquation automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BlockEquation extends Block {
    private Equation equation;

    @JsonSetter("equation")
    public void setEquation(Equation equation) {
        this.equation = equation;
    }

    @JsonGetter("equation")
    public Equation getEquation() {
        return this.equation;
    }
}

