/**
 * BlockBulletedListItem automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BlockBulletedListItem extends Block {
    private BulletedListItem bulletedListItem;

    @JsonSetter("bulleted_list_item")
    public void setBulletedListItem(BulletedListItem bulletedListItem) {
        this.bulletedListItem = bulletedListItem;
    }

    @JsonGetter("bulleted_list_item")
    public BulletedListItem getBulletedListItem() {
        return this.bulletedListItem;
    }
}

