/**
 * BlockLinkPreview automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BlockLinkPreview {
    private LinkPreview linkPreview;

    @JsonSetter("link_preview")
    public void setLinkPreview(LinkPreview linkPreview) {
        this.linkPreview = linkPreview;
    }

    @JsonGetter("link_preview")
    public LinkPreview getLinkPreview() {
        return this.linkPreview;
    }
}

