/**
 * BlockPDF automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BlockPDF extends Block {
    private PDF pdf;

    @JsonSetter("pdf")
    public void setPdf(PDF pdf) {
        this.pdf = pdf;
    }

    @JsonGetter("pdf")
    public PDF getPdf() {
        return this.pdf;
    }
}

