/**
 * BlockParagraph automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BlockParagraph extends Block {
    private Paragraph paragraph;

    @JsonSetter("paragraph")
    public void setParagraph(Paragraph paragraph) {
        this.paragraph = paragraph;
    }

    @JsonGetter("paragraph")
    public Paragraph getParagraph() {
        return this.paragraph;
    }
}

