/**
 * BlockCode automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BlockCode extends Block {
    private Code code;

    @JsonSetter("code")
    public void setCode(Code code) {
        this.code = code;
    }

    @JsonGetter("code")
    public Code getCode() {
        return this.code;
    }
}

