/**
 * BlockImage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BlockImage extends Block {
    private FileObject image;

    @JsonSetter("image")
    public void setImage(FileObject image) {
        this.image = image;
    }

    @JsonGetter("image")
    public FileObject getImage() {
        return this.image;
    }
}

