/**
 * BlockNumberedListItem automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BlockNumberedListItem extends Block {
    private NumberedListItem numberedListItem;

    @JsonSetter("numbered_list_item")
    public void setNumberedListItem(NumberedListItem numberedListItem) {
        this.numberedListItem = numberedListItem;
    }

    @JsonGetter("numbered_list_item")
    public NumberedListItem getNumberedListItem() {
        return this.numberedListItem;
    }
}

