/**
 * BlockQuote automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BlockQuote extends Block {
    private Quote quote;

    @JsonSetter("quote")
    public void setQuote(Quote quote) {
        this.quote = quote;
    }

    @JsonGetter("quote")
    public Quote getQuote() {
        return this.quote;
    }
}

