/**
 * Bookmark automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class Bookmark {
    private java.util.List<RichText> caption;
    private String url;

    @JsonSetter("caption")
    public void setCaption(java.util.List<RichText> caption) {
        this.caption = caption;
    }

    @JsonGetter("caption")
    public java.util.List<RichText> getCaption() {
        return this.caption;
    }

    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    @JsonGetter("url")
    public String getUrl() {
        return this.url;
    }
}

