/**
 * BulletedListItem automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class BulletedListItem {
    private java.util.List<BulletedListItem> richText;
    private String color;
    private java.util.List<Block> children;

    @JsonSetter("rich_text")
    public void setRichText(java.util.List<BulletedListItem> richText) {
        this.richText = richText;
    }

    @JsonGetter("rich_text")
    public java.util.List<BulletedListItem> getRichText() {
        return this.richText;
    }

    @JsonSetter("color")
    public void setColor(String color) {
        this.color = color;
    }

    @JsonGetter("color")
    public String getColor() {
        return this.color;
    }

    @JsonSetter("children")
    public void setChildren(java.util.List<Block> children) {
        this.children = children;
    }

    @JsonGetter("children")
    public java.util.List<Block> getChildren() {
        return this.children;
    }
}

