/**
 * Callout automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class Callout {
    private java.util.List<RichText> richText;
    private Icon icon;
    private String color;

    @JsonSetter("rich_text")
    public void setRichText(java.util.List<RichText> richText) {
        this.richText = richText;
    }

    @JsonGetter("rich_text")
    public java.util.List<RichText> getRichText() {
        return this.richText;
    }

    @JsonSetter("icon")
    public void setIcon(Icon icon) {
        this.icon = icon;
    }

    @JsonGetter("icon")
    public Icon getIcon() {
        return this.icon;
    }

    @JsonSetter("color")
    public void setColor(String color) {
        this.color = color;
    }

    @JsonGetter("color")
    public String getColor() {
        return this.color;
    }
}

