/**
 * DatabaseParentId automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class DatabaseParentId extends ParentId {
    private String databaseId;

    @JsonSetter("database_id")
    public void setDatabaseId(String databaseId) {
        this.databaseId = databaseId;
    }

    @JsonGetter("database_id")
    public String getDatabaseId() {
        return this.databaseId;
    }
}

