/**
 * Database automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.time.LocalDateTime;
import java.util.List;
public class Database {
    private String object;
    private String id;
    private LocalDateTime createdTime;
    private LocalDateTime lastEditedTime;
    private DatabaseIcon icon;
    private DatabaseCover cover;
    private String url;
    private List<DatabaseTitle> title;
    private List<DatabaseTitle> description;
    @JsonSetter("object")
    public void setObject(String object) {
        this.object = object;
    }
    @JsonGetter("object")
    public String getObject() {
        return this.object;
    }
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }
    @JsonGetter("id")
    public String getId() {
        return this.id;
    }
    @JsonSetter("created_time")
    public void setCreatedTime(LocalDateTime createdTime) {
        this.createdTime = createdTime;
    }
    @JsonGetter("created_time")
    public LocalDateTime getCreatedTime() {
        return this.createdTime;
    }
    @JsonSetter("last_edited_time")
    public void setLastEditedTime(LocalDateTime lastEditedTime) {
        this.lastEditedTime = lastEditedTime;
    }
    @JsonGetter("last_edited_time")
    public LocalDateTime getLastEditedTime() {
        return this.lastEditedTime;
    }
    @JsonSetter("icon")
    public void setIcon(DatabaseIcon icon) {
        this.icon = icon;
    }
    @JsonGetter("icon")
    public DatabaseIcon getIcon() {
        return this.icon;
    }
    @JsonSetter("cover")
    public void setCover(DatabaseCover cover) {
        this.cover = cover;
    }
    @JsonGetter("cover")
    public DatabaseCover getCover() {
        return this.cover;
    }
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }
    @JsonGetter("url")
    public String getUrl() {
        return this.url;
    }
    @JsonSetter("title")
    public void setTitle(List<DatabaseTitle> title) {
        this.title = title;
    }
    @JsonGetter("title")
    public List<DatabaseTitle> getTitle() {
        return this.title;
    }
    @JsonSetter("description")
    public void setDescription(List<DatabaseTitle> description) {
        this.description = description;
    }
    @JsonGetter("description")
    public List<DatabaseTitle> getDescription() {
        return this.description;
    }
}
