/**
 * DatabaseAnnotations automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class DatabaseAnnotations {
    private Boolean bold;
    private Boolean italic;
    private Boolean strikethrough;
    private Boolean underline;
    private Boolean code;
    private String color;

    @JsonSetter("bold")
    public void setBold(Boolean bold) {
        this.bold = bold;
    }

    @JsonGetter("bold")
    public Boolean getBold() {
        return this.bold;
    }

    @JsonSetter("italic")
    public void setItalic(Boolean italic) {
        this.italic = italic;
    }

    @JsonGetter("italic")
    public Boolean getItalic() {
        return this.italic;
    }

    @JsonSetter("strikethrough")
    public void setStrikethrough(Boolean strikethrough) {
        this.strikethrough = strikethrough;
    }

    @JsonGetter("strikethrough")
    public Boolean getStrikethrough() {
        return this.strikethrough;
    }

    @JsonSetter("underline")
    public void setUnderline(Boolean underline) {
        this.underline = underline;
    }

    @JsonGetter("underline")
    public Boolean getUnderline() {
        return this.underline;
    }

    @JsonSetter("code")
    public void setCode(Boolean code) {
        this.code = code;
    }

    @JsonGetter("code")
    public Boolean getCode() {
        return this.code;
    }

    @JsonSetter("color")
    public void setColor(String color) {
        this.color = color;
    }

    @JsonGetter("color")
    public String getColor() {
        return this.color;
    }
}

