/**
 * EmojiIcon automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class EmojiIcon extends Icon {
    private String emoji;

    @JsonSetter("emoji")
    public void setEmoji(String emoji) {
        this.emoji = emoji;
    }

    @JsonGetter("emoji")
    public String getEmoji() {
        return this.emoji;
    }
}

