/**
 * ExternalIcon automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class ExternalIcon extends Icon {
    private External external;

    @JsonSetter("external")
    public void setExternal(External external) {
        this.external = external;
    }

    @JsonGetter("external")
    public External getExternal() {
        return this.external;
    }
}

