/**
 * FileIcon automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class FileIcon extends Icon {
    private File file;

    @JsonSetter("file")
    public void setFile(File file) {
        this.file = file;
    }

    @JsonGetter("file")
    public File getFile() {
        return this.file;
    }
}

