/**
 * File automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class File {
    private String url;
    private java.time.LocalDateTime expiryTime;

    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    @JsonGetter("url")
    public String getUrl() {
        return this.url;
    }

    @JsonSetter("expiry_time")
    public void setExpiryTime(java.time.LocalDateTime expiryTime) {
        this.expiryTime = expiryTime;
    }

    @JsonGetter("expiry_time")
    public java.time.LocalDateTime getExpiryTime() {
        return this.expiryTime;
    }
}

