/**
 * Icon automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
@JsonSubTypes({
    @JsonSubTypes.Type(value = EmojiIcon.class, name = "emoji"),
    @JsonSubTypes.Type(value = FileIcon.class, name = "file"),
    @JsonSubTypes.Type(value = ExternalIcon.class, name = "external"),
})
public abstract class Icon {
    private String type;

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }
}

