/**
 * ParentId automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
@JsonSubTypes({
    @JsonSubTypes.Type(value = DatabaseParentId.class, name = "database_id"),
    @JsonSubTypes.Type(value = PageParentId.class, name = "page_id"),
    @JsonSubTypes.Type(value = BlockParentId.class, name = "block_id"),
    @JsonSubTypes.Type(value = WorkspaceParentId.class, name = "workspace"),
})
public abstract class ParentId {
    private String type;

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }
}

