/**
 * PDF automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type")
@JsonSubTypes({
    @JsonSubTypes.Type(value = PDFExternal.class, name = "external"),
    @JsonSubTypes.Type(value = PDFFile.class, name = "file"),
})
public abstract class PDF {
    private java.util.List<RichText> caption;
    private String type;

    @JsonSetter("caption")
    public void setCaption(java.util.List<RichText> caption) {
        this.caption = caption;
    }

    @JsonGetter("caption")
    public java.util.List<RichText> getCaption() {
        return this.caption;
    }

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }
}

