/**
 * PDFExternal automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class PDFExternal extends PDF {
    private ExternalObject external;

    @JsonSetter("external")
    public void setExternal(ExternalObject external) {
        this.external = external;
    }

    @JsonGetter("external")
    public ExternalObject getExternal() {
        return this.external;
    }
}

