/**
 * PDFFile automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class PDFFile extends PDF {
    private FileObject file;

    @JsonSetter("file")
    public void setFile(FileObject file) {
        this.file = file;
    }

    @JsonGetter("file")
    public FileObject getFile() {
        return this.file;
    }
}

