/**
 * RichTextText automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class RichTextText extends RichText {
    private Text text;

    @JsonSetter("text")
    public void setText(Text text) {
        this.text = text;
    }

    @JsonGetter("text")
    public Text getText() {
        return this.text;
    }
}

