/**
 * Text automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.notion;

import com.fasterxml.jackson.annotation.*;

public class Text {
    private String content;
    private Link link;

    @JsonSetter("content")
    public void setContent(String content) {
        this.content = content;
    }

    @JsonGetter("content")
    public String getContent() {
        return this.content;
    }

    @JsonSetter("link")
    public void setLink(Link link) {
        this.link = link;
    }

    @JsonGetter("link")
    public Link getLink() {
        return this.link;
    }
}

